In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier

reviews = [
    "Excellent product",
    "Very good quality",
    "Worth buying",
    "Bad product",
    "Waste of money",
    "Poor quality"
]

labels = [
    "positive",
    "positive",
    "positive",
    "negative",
    "negative",
    "negative"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(reviews)

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X, labels)

prediction = model.predict(
    vectorizer.transform(["Amazing quality"])
)

print("Prediction:", prediction[0])
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

df = pd.DataFrame({
    "tempo":[120,130,110,90,95,140,100,85],
    "danceability":[80,85,60,40,45,90,55,35],
    "energy":[90,95,65,40,50,98,60,35],
    "playlist":[1,1,1,0,0,1,0,0]
})

X = df[["tempo","danceability","energy"]]
y = df["playlist"]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.25,random_state=42
)

euclidean_model = KNeighborsClassifier(
    n_neighbors=3,
    metric="euclidean"
)

euclidean_model.fit(X_train,y_train)

manhattan_model = KNeighborsClassifier(
    n_neighbors=3,
    metric="manhattan"
)

manhattan_model.fit(X_train,y_train)

print(
    "Euclidean Accuracy:",
    euclidean_model.score(X_test,y_test)
)

print(
    "Manhattan Accuracy:",
    manhattan_model.score(X_test,y_test)
)


## Question 3: Gaussian Naive Bayes for IRCTC Booking

import pandas as pd
from sklearn.naive_bayes import GaussianNB

df = pd.DataFrame({
    "booking_time":[5,10,2,8,3,12],
    "train_popularity":[90,80,95,60,88,50],
    "travel_day":[1,0,1,0,1,0],
    "status":[0,1,0,1,0,1]
})

X = df[[
    "booking_time",
    "train_popularity",
    "travel_day"
]]

y = df["status"]

model = GaussianNB()

model.fit(X,y)

prediction = model.predict([[4,85,1]])

print(
    "Prediction:",
    "Confirmed" if prediction[0]==1 else "Waitlisted"
)


## Question 4: Multinomial Naive Bayes for WhatsApp Messages

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

messages = [
    "See you tomorrow",
    "Meeting at 5 PM",
    "Win a free iPhone",
    "Limited offer click now",
    "Family trip this weekend",
    "Project discussion group"
]

labels = [
    "personal",
    "group",
    "spam",
    "spam",
    "personal",
    "group"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(messages)

model = MultinomialNB()

model.fit(X,labels)

predictions = model.predict(X)

cm = confusion_matrix(
    labels,
    predictions
)

print("Confusion Matrix")

print(cm)

## Question 5: KNN Image Classifier

import numpy as np
from sklearn.neighbors import KNeighborsClassifier

bat_images = np.random.randint(
    0,100,(10,64)
)

football_images = np.random.randint(
    150,255,(10,64)
)

X = np.vstack(
    (bat_images,football_images)
)

y = ["bat"]*10 + ["football"]*10

model = KNeighborsClassifier(
    n_neighbors=3
)

model.fit(X,y)

test_image = np.random.randint(
    0,100,(1,64)
)

prediction = model.predict(test_image)

print("Prediction:",prediction[0])



Prediction: positive
Euclidean Accuracy: 1.0
Manhattan Accuracy: 1.0
Prediction: Waitlisted
Confusion Matrix
[[2 0 0]
 [0 2 0]
 [0 0 2]]
Prediction: bat


c:\Users\Aaryan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
